name: harusaki
description: Conventional SpringSimulations
version: 0.0.3
homepage: https://github.com/XLNT/harusaki
author: Matt Condon (shrugs) <matt@bydot.app>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  test: ^1.6.0
